/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    get: operations["health_check"];
  };
}

export interface components {
  schemas: {};
}

export interface operations {
  health_check: {
    responses: {
      200: {
        content: {
          "application/json": {
            status: string;
          };
        };
      };
    };
  };
}
