-- منح صلاحيات للمستخدم audit على schema public
GRANT ALL ON SCHEMA public TO audit;
GRANT ALL ON ALL TABLES IN SCHEMA public TO audit;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO audit;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO audit;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO audit;
